apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
  #- configmap.yaml
commonLabels:
  app: friendy-dev-server

configMapGenerator:
- files:
  - settings.py
  name: friendy-dev-configmap

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: friendy-server

patchesStrategicMerge:
- nodeport-patch.yaml

images:
- name: server
  newName: alan0415/friendy-server
  newTag: ddc48395
