---
# Source: mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.5.1
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: false
